### ISSUE TITLE
neuer screenshot

### ISSUE THREAD

**Issue by ratnanil** [Modul-AGI/HS22#7]
https://github.com/Modul-AGI/HS22/blob/d1793f7178aa3958f4804a8bb3c5035cd9ea6761/D_Netzwerkanalyse_1/2_Vorbereitung.qmd#L36

@DLND8: Kannst du hier einen neuen Screenshot einpflegen?

**Comment by DLND8** [comment]
done with https://github.com/Modul-AGI/HS22/commit/b9fa77e8270b7d4f61fda05d9cdd9df7701a03e9
